---
ssh:
  user: vagrant
  identity_file: ~/.ssh/id_rsa-cluster-w
rhost: myhost.example.com
# sshd port
mosh_daemon_port: 22
proxies:
- link: "socks5://127.0.0.1:1080"
- link: "ss://encryption:password@myhost.example.com:1080"
- link: "relay://127.0.0.1:1081"
  last: true

## Dynamic assignments. 
# DO NOT mark the end of YAML file 
#
# local_port: $local_relay_port
# mosh_server_port: $mosh_port
#
# and have a new line at the end.